language: java

jdk:
  - openjdk8

sudo: required
services:
  - docker

script:
  - ./gradlew build

jobs:
  include:

    - env: [ NAME="integration-tests" ]
      script:
        - |
          DOCKER_HOST=unix:///var/run/docker.sock DOCKER_TLS_VERIFY= docker run -t --rm \
          -v "$HOME/.gradle":/root/.gradle/ \
          -v /var/run/docker.sock:/var/run/docker.sock \
          -v "$(pwd)":"$(pwd)" \
          -w "$(pwd)" \
          openjdk:8-jdk-alpine \
          ./gradlew integrationTest

after_success:
  - bash <(curl -s https://codecov.io/bash)