language: java

jdk:
  - openjdk8

env:
  - CODACY_PROJECT_TOKEN=32a7e2faa1854ebe97ad3e1e093b6c0b

sudo: required
services:
  - docker
  - rabbitmq
  - redis

before_install:
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r '.assets[0].browser_download_url')

script:
  - ./gradlew build
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r build/reports/jacoco/coverage.xml
